### ISSUE TITLE
Unable to load DLL 'libsass64' or one of its dependencies

### ISSUE THREAD

**Issue by Cherepoc** [w8tcha/BootstrapEmail.Net#35]
Hi! I'm trying to use this project for processing email templates at runtime. I'm getting this error whenever I create an instance of BootstrapEmail - "Unable to load DLL 'libsass64' or one of its dependencies: The specified module could not be found."
StackTrace:
System.TypeInitializationException
The type initializer for 'LibSass.Compiler.SassCompiler' threw an exception.
   at LibSass.Compiler.SassCompiler..ctor(ISassOptions sassOptions)
   at BootstrapEmail.Net.Compiler..ctor(String input, ConfigStore config, InputType type)
   at BootstrapEmail.Net.BootstrapEmail.StringCompile(String input)
   at BootstrapEmail.Net.BootstrapEmail.Compile(String input, String output, InputType type)
Is there a way to resolve this? Thanks!

**Comment by Cherepoc** [comment]
I've managed to fix that by adding libsassnetstandard to my project. Otherwise dlls are not being copied.
I've run into another issue immediately:
Could not find a part of the path 'D:\ChrisNakea\om-web\OurMayberry\OurMayberry.WebApi.IntegrationTests\bin\Debug\net8.0\core\templates\body.html'
I beleive I need to copy those files from the source. But again, this does not happen automatically.
Thanks!

**Comment by w8tcha** [comment]
I assume you are using the nuget package? I released a new version the missing libsass64.dll and libsass32.dll are now included also the scss and html templates (core files) are now embedded in the dll. And automatically extracted to the output folder.

**Comment by w8tcha** [comment]
The files are copied as soon as you use `bsEmail.Compile(xxxx)`

i updated the Program.cs

```c#
// See https://aka.ms/new-console-template for more information

using BootstrapEmail.Net;

Console.WriteLine("Hello, World!");

var bsEmail = new BootstrapEmail.Net.BootstrapEmail();

Console.WriteLine(bsEmail.Compile("<a href='#' class='btn btn-primary'>Some Button</a>", string.Empty, InputType.String));
```

**Comment by Cherepoc** [comment]
@w8tcha Thanks! It worked after cleanup.
