### ISSUE TITLE
Table generated from body is missing the style attribute

### ISSUE THREAD

**Issue by Cherepoc** [w8tcha/BootstrapEmail.Net#36]
Hi!
I've noticed there are some differences and errors when compiling templates in this project vs the bootstrapemail.com website. Here's an example, with source html, a result from bootstrapemail.com website, and an html result generated with this library.
[result-test.zip](https://github.com/w8tcha/BootstrapEmail.Net/files/14934418/result-test.zip)

1. Opening both results in browser reveals that in web result the card is centered and has 600px width, and lib result is not centered, and its width is trimmed to content. That's because the table inside the body does not have a style attribute. Copying the style attribute from the web result makes two results appear identical in the browser.
2. Body class "bg-light" in source is transferred into table inside body as "bg-light body" in web result, and as "bg-lightbody" in lib result.
3. Source template does not have DOCTYPE, it's added automatically to the web result, but not to the lib result.

Hope that'll be helpful. Thanks!

**Comment by w8tcha** [comment]
Issues are fixed in 1.4.3

Issue 1 is caused because of 2.
3. Doctype is now added
