### ISSUE TITLE
[1.4.3] Inline styles are not being generated

### ISSUE THREAD

**Issue by Cherepoc** [w8tcha/BootstrapEmail.Net#37]
Hi!
In the new 1.4.3 version the inline styles are not being generated at all. Here's a comparison with the web version (I haven't included html previously generated with the 1.4.2 version, but it did have inline styles).
[result-test.zip](https://github.com/w8tcha/BootstrapEmail.Net/files/14947030/result-test.zip)
One more catch - original style elements in the head are not being removed in the lib, but are removed in the web.
Thanks!

**Comment by w8tcha** [comment]
Both issues should be fixed in 1.4.4
