### ISSUE TITLE
Wrong background color is applied to the table generated from body

### ISSUE THREAD

**Issue by Cherepoc** [w8tcha/BootstrapEmail.Net#39]
Hi!
When defining custom classes with the background color and applying them to the body, the table generated from the body has wrong background color. Here's an example and comparison with the web version:
[result-test.zip](https://github.com/w8tcha/BootstrapEmail.Net/files/14956783/result-test.zip)
In the example there's grey background defined as a class in styles and applied to the body. There's also a white card inside.
The code generated from the web is correct, and shows grey background and white card. The code generated with this library has white background around the card too. That happens because the table inside the body has explicit white background being set in the table attributes and style.

**Comment by w8tcha** [comment]
At the moment all inline css are ignored. 

The better solution would be to use additional scss files, this already works.

However this will be fixed in the next release.
