### ISSUE TITLE
How to add sass files

### ISSUE THREAD

**Issue by Cherepoc** [w8tcha/BootstrapEmail.Net#40]
Hi! Can you please direct me or give me an example how to use sass files to add new css classes?
I want to add a new background color task using the sass background-color-util. I believe I can add another sass directory and the files will be included and compiled. How can I do that?
Thanks!

**Comment by w8tcha** [comment]
By default if instiate the compiler with...

`var bsEmail = new BootstrapEmail();` it used the default configuration.

You can change this if you set the config via

```c#
 var config = new ConfigStore();

// core is the default folder 
config.sass_location = "/core"

// extra folder locations for scss files
config.sass_load_paths = new[] { "/more-files" };

var bsEmail = new BootstrapEmail();
```

There are two main scss files the `bootstrap-head.scss` which will be inserted in to the head and the `bootstrap-email.scss` which is uses for inlining.

all scss files in the folder core will be loaded an parsed. you can also define additional folder for loading and parsing via `config.sass_load_paths`

**Comment by Cherepoc** [comment]
Hi! I've tried to add a new color in a file in that directory, with no success. Here's how my scss file looks like:
```
$custom-colors: (
  "outer": #E5E5E5
) !default;

$all-colors: map-merge($all-colors, $custom-colors);
```
If I want to add another color using custom style files, how should I do that?

**Comment by w8tcha** [comment]
If you want to add a new color use ...

```scss
$outer: #E5E5E5 !default;
```

and then you can apply it for example to a class

```scss
.bg-outer {
	background-color: $outer
}
```

**Comment by w8tcha** [comment]
Sorry my provided solution wont work. It was not the right option. 

As solution to add extra styles add the scss file you want import to the `bootstrap-email.scss`

```scss
@import 'scss/custom';
```

then the file `custom.scss` needs to be placed in the folder core/scss. This should work fine with the latest version

**Comment by w8tcha** [comment]
> It seems that if the core directory is present, then the core files from the library are not being copied.

Correct only if the folder doesnt exist it as extracted from the dll.

As solution use a different folder for example **styles** then place the bootstrap-email.scss and the custom.scss in there ...

with an extra line to import the custom style

```scss
@import 'styles/custom';
```

and in the config set the  `sass_email_location`

```c#
new BootstrapEmail.Net.BootstrapEmail(new ConfigStore(){sass_email_location = "styles/"})
```

--------------------

here is the full example...

[BootstrapEmailExample.zip](https://github.com/w8tcha/BootstrapEmail.Net/files/15019981/BootstrapEmailExample.zip)

**Comment by Cherepoc** [comment]
It works, thanks!
