### ISSUE TITLE
Concurrency errors when using precompiled css

### ISSUE THREAD

**Issue by Cherepoc** [w8tcha/BootstrapEmail.Net#48]
Hi!
Tried the sass precompilation approach recently, I get errors when I try to do multiple renderings at the same time, here's an example.
[BootstrapEmailExample.zip](https://github.com/w8tcha/BootstrapEmail.Net/files/15214115/BootstrapEmailExample.zip)
The error is: The process cannot access the file 'D:\Projects\BootstrapEmailExample\ConsoleExample\bin\Debug\net8.0\core\bootstrap-email.scss' because it is being used by another process.
I also noticed that if the css files are not found then the usual sass compilation takes place. That can be misleading, can there be a switch that turns off sass in the library, and in case the css files are not found it throws an error? That will help in debugging.
Thanks!

**Comment by w8tcha** [comment]
The error is fixed 

> I also noticed that if the css files are not found then the usual sass compilation takes place. That can be misleading, can there be a switch that turns off sass in the library, and in case the css files are not found it throws an error?

it now throws a filenotfoundexception

**Comment by Cherepoc** [comment]
Thanks! I think you need to increment the version though, nuget still has the pre-fix version.
